/* Original collection names and part labels transcribed from the supplied references.
 * Add authorized video/audio URLs to each lesson's `source` to enable native playback.
 * Unavailable media is clearly identified inside the local learning workspace.
 */
window.ORM_CATEGORIES = [
  { name: 'All topics', icon: 'grid' },
  { name: 'Getting started', icon: 'compass' },
  { name: 'Chart reading', icon: 'chart' },
  { name: 'Options strategies', icon: 'sliders' },
  { name: 'Commodities', icon: 'layers' },
  { name: 'Practice & process', icon: 'target' },
  { name: 'Stock market', icon: 'trending-up' }
];
(() => {
  const parts = count => Array.from({ length: count }, (_, i) => ({ title: `Part ${i + 1}`, source: null }));
  window.ORM_COURSES = [
    { id: 'get-going', title: 'Get Going Seminar', category: 'Getting started', tag: 'START HERE', image: 'assets/get-going.webp', icon: 'compass', tone: '', format: 'Video', author: 'Ken Roberts', description: 'Find your bearings with an introduction to Ken Roberts’ approach to commodity markets.', lessons: parts(4), resources: ['The Options Profits Insurance Plan'] },
    { id: 'retracement', title: 'The 50% Retracement', category: 'Chart reading', tag: 'CHARTS & PERSPECTIVE', image: 'assets/retracement.webp', icon: 'chart', tone: '', format: 'Video', author: 'Ken Roberts', description: 'Explore Ken Roberts’ original lessons on the 50% retracement, with the accompanying workbook and quiz.', lessons: parts(2), resources: ['50% Retracement Workbook & Quiz'] },
    { id: 'tools', title: 'Tools of the Trade', category: 'Chart reading', tag: 'THE THREE-DAY SEMINAR', image: 'assets/tools.webp', icon: 'chart', tone: 'sand', format: 'Video', author: 'Ken Roberts', description: 'A three-day seminar collection, supported by chart books and original reference materials.', lessons: [1,2,3].flatMap(day => Array.from({ length: day === 1 ? 4 : 3 }, (_, i) => ({ title: `Day ${day} · Part ${i + 1}`, source: null }))), resources: ['Chart book · Day 1 of 3', 'Chart book · Day 2 of 3', 'Chart book · Day 3 of 3', 'The Options Profits Insurance Plan', 'Success Summit · The Options Profits Insurance Plan', 'Sir John Templeton', 'Why the Front Month is the Only Daily Chart I Need', 'A New Way to Prioritize Your Trades', 'Printable Note for Charts'] },
    { id: 'real-people', title: 'Real People, Real Money', category: 'Getting started', tag: 'FROM THE ARCHIVE', image: 'assets/real-people.webp', icon: 'message-circle', tone: 'sand', format: 'Video', author: 'Ken Roberts', description: 'Historical interviews with course members, recorded while the Ken Roberts Company was active.', note: 'These historical testimonials are individual experiences and do not represent typical results or a promise of future performance.', lessons: parts(3), resources: [] },
    { id: 'market-now', title: 'My Favorite Market Now', category: 'Chart reading', tag: 'MARKET PERSPECTIVE', icon: 'trending-up', tone: 'blue', format: 'Video', author: 'Ken Roberts', description: 'An original classroom recording, a broker conversation, and Ken’s special call to Bob Brinker.', lessons: [...parts(2), { title: 'A special call with Bob Brinker', source: null }], resources: [] },
    { id: 'advanced-options', title: 'Advanced Options Workshop', category: 'Options strategies', tag: 'OPTIONS IN FOCUS', icon: 'sliders', tone: 'dark', format: 'Video', author: 'Ken Roberts', description: 'A four-part workshop from the original archive, focused on a deeper study of options.', lessons: parts(4), resources: [] },
    { id: 'cash-basis', title: 'Cash Basis Connection', category: 'Commodities', tag: 'COMMODITY FOUNDATIONS', icon: 'layers', tone: 'sand', format: 'Audio / video', author: 'Ken Roberts', description: 'The Cash Basis Connection recordings and course book, alongside A Call From Ken.', lessons: [{ title: 'Cash Basis Connection recording', source: null }, { title: 'A Call From Ken · Parts 1 & 2', source: null }], resources: ['Cash Basis Connection course book'] },
    { id: 'delta-options', title: 'The Delta Options Trading Strategy', category: 'Options strategies', tag: 'ORIGINAL COURSE SERIES', icon: 'route', tone: '', format: 'Video', author: 'Ken Roberts', description: 'Explore the original Delta Options Trading Strategy course recordings and companion book.', lessons: [{ title: 'Tapes 1 & 2', source: null }, { title: 'Tapes 3 & 4', source: null }], resources: ['The Delta Options Trading Strategy course book'] },
    { id: 'money-manual', title: 'The TWMPMM Workshop', category: 'Commodities', tag: 'THE MONEY MANUAL', image: 'assets/workshop.webp', icon: 'book-open', tone: '', format: 'Video', author: 'Ken Roberts', description: 'Six workshop recordings from The World’s Most Powerful Money Manual collection.', note: 'The original books are out of print. Case Study Book pages 3–4 and 41–42 are missing in the supplied archive.', lessons: parts(6), resources: ['The World’s Most Powerful Money Manual', 'The World’s Most Powerful Money Manual · Case Study Book'] },
    { id: 'roundtable', title: 'Roundtable Seminar', category: 'Commodities', tag: 'LEARNING THROUGH DISCUSSION', icon: 'message-circle', tone: 'blue', format: 'Video', author: 'Ken Roberts', description: 'A five-part seminar collection from the original Ken Roberts teaching archive.', lessons: parts(5), resources: [] },
    { id: 'paper-trading', title: 'Guide to Paper Trading', category: 'Practice & process', tag: 'PRACTICE WITH PURPOSE', icon: 'target', tone: '', format: 'Video', author: 'Ken Roberts', description: 'Explore the original two-part guide to paper trading and developing a thoughtful learning process.', lessons: parts(2), resources: [] },
    { id: 'advanced-commodities', title: 'Ken Roberts and Ted Warren', category: 'Commodities', tag: 'TWO TEACHING PERSPECTIVES', icon: 'book-open', tone: 'sand', format: 'Video', author: 'Ken Roberts & Ted Warren', description: 'Ted Warren’s Advanced Commodity Trading Techniques, with the original companion manual.', lessons: [{ title: 'Advanced Commodity Trading Techniques', source: null }], resources: ['Advanced Commodity Trading Techniques · The Manual'] },
    { id: 'commodity-seminar', title: 'Ted Warren Commodity Seminar', category: 'Commodities', tag: 'THE HISTORICAL AUDIO ARCHIVE', icon: 'headphones', tone: 'dark', format: 'Audio', author: 'Ted Warren', description: 'Listen to the historical commodity seminar recordings from March 4, 1978, in the original archive.', lessons: parts(2), resources: [] },
    { id: 'stock-workshop', title: 'Ted Warren Stock Workshop', category: 'Stock market', tag: 'THE STOCK MARKET COLLECTION', image: 'assets/ted-warren.webp', icon: 'chart', tone: 'blue', format: 'Video', author: 'Ted Warren', description: 'A ten-part historical workshop, accompanied by Ted Warren’s stock market books and workbook.', lessons: parts(10), resources: ['How to Make the Stock Market Make Money for You', 'Ted Warren in an Hour', 'Ted Warren Seminar Workbook'] }
  ];
})();
